// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: advance.proto

#ifndef PROTOBUF_advance_2eproto__INCLUDED
#define PROTOBUF_advance_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace advance {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_advance_2eproto();
void protobuf_AssignDesc_advance_2eproto();
void protobuf_ShutdownFile_advance_2eproto();

class Args;
class Args_L_new;
class Args_State;
class Args_State_m_D_old;
class Args_State_m_W_old;
class Args_State_m_D_new;
class Args_State_m_W_new;
class Args_State_m_R;
class Args_State_m_Vbar_prime;
class Args_State_m_Vbar_prime_dot;
class Args_State_m_Dbar_prime;
class Args_State_m_Wbar;
class Args_State_taylor_state;

// ===================================================================

class Args_L_new : public ::google::protobuf::Message {
 public:
  Args_L_new();
  virtual ~Args_L_new();

  Args_L_new(const Args_L_new& from);

  inline Args_L_new& operator=(const Args_L_new& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Args_L_new& default_instance();

  void Swap(Args_L_new* other);

  // implements Message ----------------------------------------------

  Args_L_new* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Args_L_new& from);
  void MergeFrom(const Args_L_new& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double a = 1 [packed = true];
  inline int a_size() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline double a(int index) const;
  inline void set_a(int index, double value);
  inline void add_a(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      a() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_a();

  // @@protoc_insertion_point(class_scope:advance.Args.L_new)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< double > a_;
  mutable int _a_cached_byte_size_;
  friend void  protobuf_AddDesc_advance_2eproto();
  friend void protobuf_AssignDesc_advance_2eproto();
  friend void protobuf_ShutdownFile_advance_2eproto();

  void InitAsDefaultInstance();
  static Args_L_new* default_instance_;
};
// -------------------------------------------------------------------

class Args_State_m_D_old : public ::google::protobuf::Message {
 public:
  Args_State_m_D_old();
  virtual ~Args_State_m_D_old();

  Args_State_m_D_old(const Args_State_m_D_old& from);

  inline Args_State_m_D_old& operator=(const Args_State_m_D_old& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Args_State_m_D_old& default_instance();

  void Swap(Args_State_m_D_old* other);

  // implements Message ----------------------------------------------

  Args_State_m_D_old* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Args_State_m_D_old& from);
  void MergeFrom(const Args_State_m_D_old& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double a = 1 [packed = true];
  inline int a_size() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline double a(int index) const;
  inline void set_a(int index, double value);
  inline void add_a(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      a() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_a();

  // @@protoc_insertion_point(class_scope:advance.Args.State.m_D_old)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< double > a_;
  mutable int _a_cached_byte_size_;
  friend void  protobuf_AddDesc_advance_2eproto();
  friend void protobuf_AssignDesc_advance_2eproto();
  friend void protobuf_ShutdownFile_advance_2eproto();

  void InitAsDefaultInstance();
  static Args_State_m_D_old* default_instance_;
};
// -------------------------------------------------------------------

class Args_State_m_W_old : public ::google::protobuf::Message {
 public:
  Args_State_m_W_old();
  virtual ~Args_State_m_W_old();

  Args_State_m_W_old(const Args_State_m_W_old& from);

  inline Args_State_m_W_old& operator=(const Args_State_m_W_old& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Args_State_m_W_old& default_instance();

  void Swap(Args_State_m_W_old* other);

  // implements Message ----------------------------------------------

  Args_State_m_W_old* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Args_State_m_W_old& from);
  void MergeFrom(const Args_State_m_W_old& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double a = 1 [packed = true];
  inline int a_size() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline double a(int index) const;
  inline void set_a(int index, double value);
  inline void add_a(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      a() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_a();

  // @@protoc_insertion_point(class_scope:advance.Args.State.m_W_old)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< double > a_;
  mutable int _a_cached_byte_size_;
  friend void  protobuf_AddDesc_advance_2eproto();
  friend void protobuf_AssignDesc_advance_2eproto();
  friend void protobuf_ShutdownFile_advance_2eproto();

  void InitAsDefaultInstance();
  static Args_State_m_W_old* default_instance_;
};
// -------------------------------------------------------------------

class Args_State_m_D_new : public ::google::protobuf::Message {
 public:
  Args_State_m_D_new();
  virtual ~Args_State_m_D_new();

  Args_State_m_D_new(const Args_State_m_D_new& from);

  inline Args_State_m_D_new& operator=(const Args_State_m_D_new& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Args_State_m_D_new& default_instance();

  void Swap(Args_State_m_D_new* other);

  // implements Message ----------------------------------------------

  Args_State_m_D_new* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Args_State_m_D_new& from);
  void MergeFrom(const Args_State_m_D_new& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double a = 1 [packed = true];
  inline int a_size() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline double a(int index) const;
  inline void set_a(int index, double value);
  inline void add_a(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      a() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_a();

  // @@protoc_insertion_point(class_scope:advance.Args.State.m_D_new)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< double > a_;
  mutable int _a_cached_byte_size_;
  friend void  protobuf_AddDesc_advance_2eproto();
  friend void protobuf_AssignDesc_advance_2eproto();
  friend void protobuf_ShutdownFile_advance_2eproto();

  void InitAsDefaultInstance();
  static Args_State_m_D_new* default_instance_;
};
// -------------------------------------------------------------------

class Args_State_m_W_new : public ::google::protobuf::Message {
 public:
  Args_State_m_W_new();
  virtual ~Args_State_m_W_new();

  Args_State_m_W_new(const Args_State_m_W_new& from);

  inline Args_State_m_W_new& operator=(const Args_State_m_W_new& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Args_State_m_W_new& default_instance();

  void Swap(Args_State_m_W_new* other);

  // implements Message ----------------------------------------------

  Args_State_m_W_new* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Args_State_m_W_new& from);
  void MergeFrom(const Args_State_m_W_new& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double a = 1 [packed = true];
  inline int a_size() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline double a(int index) const;
  inline void set_a(int index, double value);
  inline void add_a(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      a() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_a();

  // @@protoc_insertion_point(class_scope:advance.Args.State.m_W_new)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< double > a_;
  mutable int _a_cached_byte_size_;
  friend void  protobuf_AddDesc_advance_2eproto();
  friend void protobuf_AssignDesc_advance_2eproto();
  friend void protobuf_ShutdownFile_advance_2eproto();

  void InitAsDefaultInstance();
  static Args_State_m_W_new* default_instance_;
};
// -------------------------------------------------------------------

class Args_State_m_R : public ::google::protobuf::Message {
 public:
  Args_State_m_R();
  virtual ~Args_State_m_R();

  Args_State_m_R(const Args_State_m_R& from);

  inline Args_State_m_R& operator=(const Args_State_m_R& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Args_State_m_R& default_instance();

  void Swap(Args_State_m_R* other);

  // implements Message ----------------------------------------------

  Args_State_m_R* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Args_State_m_R& from);
  void MergeFrom(const Args_State_m_R& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double a = 1 [packed = true];
  inline int a_size() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline double a(int index) const;
  inline void set_a(int index, double value);
  inline void add_a(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      a() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_a();

  // @@protoc_insertion_point(class_scope:advance.Args.State.m_R)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< double > a_;
  mutable int _a_cached_byte_size_;
  friend void  protobuf_AddDesc_advance_2eproto();
  friend void protobuf_AssignDesc_advance_2eproto();
  friend void protobuf_ShutdownFile_advance_2eproto();

  void InitAsDefaultInstance();
  static Args_State_m_R* default_instance_;
};
// -------------------------------------------------------------------

class Args_State_m_Vbar_prime : public ::google::protobuf::Message {
 public:
  Args_State_m_Vbar_prime();
  virtual ~Args_State_m_Vbar_prime();

  Args_State_m_Vbar_prime(const Args_State_m_Vbar_prime& from);

  inline Args_State_m_Vbar_prime& operator=(const Args_State_m_Vbar_prime& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Args_State_m_Vbar_prime& default_instance();

  void Swap(Args_State_m_Vbar_prime* other);

  // implements Message ----------------------------------------------

  Args_State_m_Vbar_prime* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Args_State_m_Vbar_prime& from);
  void MergeFrom(const Args_State_m_Vbar_prime& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double a = 1 [packed = true];
  inline int a_size() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline double a(int index) const;
  inline void set_a(int index, double value);
  inline void add_a(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      a() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_a();

  // @@protoc_insertion_point(class_scope:advance.Args.State.m_Vbar_prime)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< double > a_;
  mutable int _a_cached_byte_size_;
  friend void  protobuf_AddDesc_advance_2eproto();
  friend void protobuf_AssignDesc_advance_2eproto();
  friend void protobuf_ShutdownFile_advance_2eproto();

  void InitAsDefaultInstance();
  static Args_State_m_Vbar_prime* default_instance_;
};
// -------------------------------------------------------------------

class Args_State_m_Vbar_prime_dot : public ::google::protobuf::Message {
 public:
  Args_State_m_Vbar_prime_dot();
  virtual ~Args_State_m_Vbar_prime_dot();

  Args_State_m_Vbar_prime_dot(const Args_State_m_Vbar_prime_dot& from);

  inline Args_State_m_Vbar_prime_dot& operator=(const Args_State_m_Vbar_prime_dot& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Args_State_m_Vbar_prime_dot& default_instance();

  void Swap(Args_State_m_Vbar_prime_dot* other);

  // implements Message ----------------------------------------------

  Args_State_m_Vbar_prime_dot* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Args_State_m_Vbar_prime_dot& from);
  void MergeFrom(const Args_State_m_Vbar_prime_dot& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double a = 1 [packed = true];
  inline int a_size() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline double a(int index) const;
  inline void set_a(int index, double value);
  inline void add_a(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      a() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_a();

  // @@protoc_insertion_point(class_scope:advance.Args.State.m_Vbar_prime_dot)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< double > a_;
  mutable int _a_cached_byte_size_;
  friend void  protobuf_AddDesc_advance_2eproto();
  friend void protobuf_AssignDesc_advance_2eproto();
  friend void protobuf_ShutdownFile_advance_2eproto();

  void InitAsDefaultInstance();
  static Args_State_m_Vbar_prime_dot* default_instance_;
};
// -------------------------------------------------------------------

class Args_State_m_Dbar_prime : public ::google::protobuf::Message {
 public:
  Args_State_m_Dbar_prime();
  virtual ~Args_State_m_Dbar_prime();

  Args_State_m_Dbar_prime(const Args_State_m_Dbar_prime& from);

  inline Args_State_m_Dbar_prime& operator=(const Args_State_m_Dbar_prime& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Args_State_m_Dbar_prime& default_instance();

  void Swap(Args_State_m_Dbar_prime* other);

  // implements Message ----------------------------------------------

  Args_State_m_Dbar_prime* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Args_State_m_Dbar_prime& from);
  void MergeFrom(const Args_State_m_Dbar_prime& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double a = 1 [packed = true];
  inline int a_size() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline double a(int index) const;
  inline void set_a(int index, double value);
  inline void add_a(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      a() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_a();

  // @@protoc_insertion_point(class_scope:advance.Args.State.m_Dbar_prime)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< double > a_;
  mutable int _a_cached_byte_size_;
  friend void  protobuf_AddDesc_advance_2eproto();
  friend void protobuf_AssignDesc_advance_2eproto();
  friend void protobuf_ShutdownFile_advance_2eproto();

  void InitAsDefaultInstance();
  static Args_State_m_Dbar_prime* default_instance_;
};
// -------------------------------------------------------------------

class Args_State_m_Wbar : public ::google::protobuf::Message {
 public:
  Args_State_m_Wbar();
  virtual ~Args_State_m_Wbar();

  Args_State_m_Wbar(const Args_State_m_Wbar& from);

  inline Args_State_m_Wbar& operator=(const Args_State_m_Wbar& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Args_State_m_Wbar& default_instance();

  void Swap(Args_State_m_Wbar* other);

  // implements Message ----------------------------------------------

  Args_State_m_Wbar* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Args_State_m_Wbar& from);
  void MergeFrom(const Args_State_m_Wbar& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double a = 1 [packed = true];
  inline int a_size() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline double a(int index) const;
  inline void set_a(int index, double value);
  inline void add_a(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      a() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_a();

  // @@protoc_insertion_point(class_scope:advance.Args.State.m_Wbar)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< double > a_;
  mutable int _a_cached_byte_size_;
  friend void  protobuf_AddDesc_advance_2eproto();
  friend void protobuf_AssignDesc_advance_2eproto();
  friend void protobuf_ShutdownFile_advance_2eproto();

  void InitAsDefaultInstance();
  static Args_State_m_Wbar* default_instance_;
};
// -------------------------------------------------------------------

class Args_State_taylor_state : public ::google::protobuf::Message {
 public:
  Args_State_taylor_state();
  virtual ~Args_State_taylor_state();

  Args_State_taylor_state(const Args_State_taylor_state& from);

  inline Args_State_taylor_state& operator=(const Args_State_taylor_state& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Args_State_taylor_state& default_instance();

  void Swap(Args_State_taylor_state* other);

  // implements Message ----------------------------------------------

  Args_State_taylor_state* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Args_State_taylor_state& from);
  void MergeFrom(const Args_State_taylor_state& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double a = 1 [packed = true];
  inline int a_size() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline double a(int index) const;
  inline void set_a(int index, double value);
  inline void add_a(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      a() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_a();

  // @@protoc_insertion_point(class_scope:advance.Args.State.taylor_state)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< double > a_;
  mutable int _a_cached_byte_size_;
  friend void  protobuf_AddDesc_advance_2eproto();
  friend void protobuf_AssignDesc_advance_2eproto();
  friend void protobuf_ShutdownFile_advance_2eproto();

  void InitAsDefaultInstance();
  static Args_State_taylor_state* default_instance_;
};
// -------------------------------------------------------------------

class Args_State : public ::google::protobuf::Message {
 public:
  Args_State();
  virtual ~Args_State();

  Args_State(const Args_State& from);

  inline Args_State& operator=(const Args_State& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Args_State& default_instance();

  void Swap(Args_State* other);

  // implements Message ----------------------------------------------

  Args_State* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Args_State& from);
  void MergeFrom(const Args_State& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Args_State_m_D_old m_D_old;
  typedef Args_State_m_W_old m_W_old;
  typedef Args_State_m_D_new m_D_new;
  typedef Args_State_m_W_new m_W_new;
  typedef Args_State_m_R m_R;
  typedef Args_State_m_Vbar_prime m_Vbar_prime;
  typedef Args_State_m_Vbar_prime_dot m_Vbar_prime_dot;
  typedef Args_State_m_Dbar_prime m_Dbar_prime;
  typedef Args_State_m_Wbar m_Wbar;
  typedef Args_State_taylor_state taylor_state;

  // accessors -------------------------------------------------------

  // required double m_Delta_max = 1;
  inline bool has_m_delta_max() const;
  inline void clear_m_delta_max();
  static const int kMDeltaMaxFieldNumber = 1;
  inline double m_delta_max() const;
  inline void set_m_delta_max(double value);

  // required double m_Delta = 2;
  inline bool has_m_delta() const;
  inline void clear_m_delta();
  static const int kMDeltaFieldNumber = 2;
  inline double m_delta() const;
  inline void set_m_delta(double value);

  // required double m_J = 3;
  inline bool has_m_j() const;
  inline void clear_m_j();
  static const int kMJFieldNumber = 3;
  inline double m_j() const;
  inline void set_m_j(double value);

  // required int32 m_num_iters = 4;
  inline bool has_m_num_iters() const;
  inline void clear_m_num_iters();
  static const int kMNumItersFieldNumber = 4;
  inline ::google::protobuf::int32 m_num_iters() const;
  inline void set_m_num_iters(::google::protobuf::int32 value);

  // required double m_volume_change = 5;
  inline bool has_m_volume_change() const;
  inline void clear_m_volume_change();
  static const int kMVolumeChangeFieldNumber = 5;
  inline double m_volume_change() const;
  inline void set_m_volume_change(double value);

  // required double m_tol = 6;
  inline bool has_m_tol() const;
  inline void clear_m_tol();
  static const int kMTolFieldNumber = 6;
  inline double m_tol() const;
  inline void set_m_tol(double value);

  // required double m_K = 7;
  inline bool has_m_k() const;
  inline void clear_m_k();
  static const int kMKFieldNumber = 7;
  inline double m_k() const;
  inline void set_m_k(double value);

  // required double m_G = 8;
  inline bool has_m_g() const;
  inline void clear_m_g();
  static const int kMGFieldNumber = 8;
  inline double m_g() const;
  inline void set_m_g(double value);

  // @@protoc_insertion_point(class_scope:advance.Args.State)
 private:
  inline void set_has_m_delta_max();
  inline void clear_has_m_delta_max();
  inline void set_has_m_delta();
  inline void clear_has_m_delta();
  inline void set_has_m_j();
  inline void clear_has_m_j();
  inline void set_has_m_num_iters();
  inline void clear_has_m_num_iters();
  inline void set_has_m_volume_change();
  inline void clear_has_m_volume_change();
  inline void set_has_m_tol();
  inline void clear_has_m_tol();
  inline void set_has_m_k();
  inline void clear_has_m_k();
  inline void set_has_m_g();
  inline void clear_has_m_g();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double m_delta_max_;
  double m_delta_;
  double m_j_;
  double m_volume_change_;
  double m_tol_;
  double m_k_;
  double m_g_;
  ::google::protobuf::int32 m_num_iters_;
  friend void  protobuf_AddDesc_advance_2eproto();
  friend void protobuf_AssignDesc_advance_2eproto();
  friend void protobuf_ShutdownFile_advance_2eproto();

  void InitAsDefaultInstance();
  static Args_State* default_instance_;
};
// -------------------------------------------------------------------

class Args : public ::google::protobuf::Message {
 public:
  Args();
  virtual ~Args();

  Args(const Args& from);

  inline Args& operator=(const Args& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Args& default_instance();

  void Swap(Args* other);

  // implements Message ----------------------------------------------

  Args* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Args& from);
  void MergeFrom(const Args& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Args_L_new L_new;
  typedef Args_State State;

  // accessors -------------------------------------------------------

  // required double delta_t = 1;
  inline bool has_delta_t() const;
  inline void clear_delta_t();
  static const int kDeltaTFieldNumber = 1;
  inline double delta_t() const;
  inline void set_delta_t(double value);

  // required double volume_change = 2;
  inline bool has_volume_change() const;
  inline void clear_volume_change();
  static const int kVolumeChangeFieldNumber = 2;
  inline double volume_change() const;
  inline void set_volume_change(double value);

  // @@protoc_insertion_point(class_scope:advance.Args)
 private:
  inline void set_has_delta_t();
  inline void clear_has_delta_t();
  inline void set_has_volume_change();
  inline void clear_has_volume_change();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double delta_t_;
  double volume_change_;
  friend void  protobuf_AddDesc_advance_2eproto();
  friend void protobuf_AssignDesc_advance_2eproto();
  friend void protobuf_ShutdownFile_advance_2eproto();

  void InitAsDefaultInstance();
  static Args* default_instance_;
};
// ===================================================================


// ===================================================================

// Args_L_new

// repeated double a = 1 [packed = true];
inline int Args_L_new::a_size() const {
  return a_.size();
}
inline void Args_L_new::clear_a() {
  a_.Clear();
}
inline double Args_L_new::a(int index) const {
  // @@protoc_insertion_point(field_get:advance.Args.L_new.a)
  return a_.Get(index);
}
inline void Args_L_new::set_a(int index, double value) {
  a_.Set(index, value);
  // @@protoc_insertion_point(field_set:advance.Args.L_new.a)
}
inline void Args_L_new::add_a(double value) {
  a_.Add(value);
  // @@protoc_insertion_point(field_add:advance.Args.L_new.a)
}
inline const ::google::protobuf::RepeatedField< double >&
Args_L_new::a() const {
  // @@protoc_insertion_point(field_list:advance.Args.L_new.a)
  return a_;
}
inline ::google::protobuf::RepeatedField< double >*
Args_L_new::mutable_a() {
  // @@protoc_insertion_point(field_mutable_list:advance.Args.L_new.a)
  return &a_;
}

// -------------------------------------------------------------------

// Args_State_m_D_old

// repeated double a = 1 [packed = true];
inline int Args_State_m_D_old::a_size() const {
  return a_.size();
}
inline void Args_State_m_D_old::clear_a() {
  a_.Clear();
}
inline double Args_State_m_D_old::a(int index) const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_D_old.a)
  return a_.Get(index);
}
inline void Args_State_m_D_old::set_a(int index, double value) {
  a_.Set(index, value);
  // @@protoc_insertion_point(field_set:advance.Args.State.m_D_old.a)
}
inline void Args_State_m_D_old::add_a(double value) {
  a_.Add(value);
  // @@protoc_insertion_point(field_add:advance.Args.State.m_D_old.a)
}
inline const ::google::protobuf::RepeatedField< double >&
Args_State_m_D_old::a() const {
  // @@protoc_insertion_point(field_list:advance.Args.State.m_D_old.a)
  return a_;
}
inline ::google::protobuf::RepeatedField< double >*
Args_State_m_D_old::mutable_a() {
  // @@protoc_insertion_point(field_mutable_list:advance.Args.State.m_D_old.a)
  return &a_;
}

// -------------------------------------------------------------------

// Args_State_m_W_old

// repeated double a = 1 [packed = true];
inline int Args_State_m_W_old::a_size() const {
  return a_.size();
}
inline void Args_State_m_W_old::clear_a() {
  a_.Clear();
}
inline double Args_State_m_W_old::a(int index) const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_W_old.a)
  return a_.Get(index);
}
inline void Args_State_m_W_old::set_a(int index, double value) {
  a_.Set(index, value);
  // @@protoc_insertion_point(field_set:advance.Args.State.m_W_old.a)
}
inline void Args_State_m_W_old::add_a(double value) {
  a_.Add(value);
  // @@protoc_insertion_point(field_add:advance.Args.State.m_W_old.a)
}
inline const ::google::protobuf::RepeatedField< double >&
Args_State_m_W_old::a() const {
  // @@protoc_insertion_point(field_list:advance.Args.State.m_W_old.a)
  return a_;
}
inline ::google::protobuf::RepeatedField< double >*
Args_State_m_W_old::mutable_a() {
  // @@protoc_insertion_point(field_mutable_list:advance.Args.State.m_W_old.a)
  return &a_;
}

// -------------------------------------------------------------------

// Args_State_m_D_new

// repeated double a = 1 [packed = true];
inline int Args_State_m_D_new::a_size() const {
  return a_.size();
}
inline void Args_State_m_D_new::clear_a() {
  a_.Clear();
}
inline double Args_State_m_D_new::a(int index) const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_D_new.a)
  return a_.Get(index);
}
inline void Args_State_m_D_new::set_a(int index, double value) {
  a_.Set(index, value);
  // @@protoc_insertion_point(field_set:advance.Args.State.m_D_new.a)
}
inline void Args_State_m_D_new::add_a(double value) {
  a_.Add(value);
  // @@protoc_insertion_point(field_add:advance.Args.State.m_D_new.a)
}
inline const ::google::protobuf::RepeatedField< double >&
Args_State_m_D_new::a() const {
  // @@protoc_insertion_point(field_list:advance.Args.State.m_D_new.a)
  return a_;
}
inline ::google::protobuf::RepeatedField< double >*
Args_State_m_D_new::mutable_a() {
  // @@protoc_insertion_point(field_mutable_list:advance.Args.State.m_D_new.a)
  return &a_;
}

// -------------------------------------------------------------------

// Args_State_m_W_new

// repeated double a = 1 [packed = true];
inline int Args_State_m_W_new::a_size() const {
  return a_.size();
}
inline void Args_State_m_W_new::clear_a() {
  a_.Clear();
}
inline double Args_State_m_W_new::a(int index) const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_W_new.a)
  return a_.Get(index);
}
inline void Args_State_m_W_new::set_a(int index, double value) {
  a_.Set(index, value);
  // @@protoc_insertion_point(field_set:advance.Args.State.m_W_new.a)
}
inline void Args_State_m_W_new::add_a(double value) {
  a_.Add(value);
  // @@protoc_insertion_point(field_add:advance.Args.State.m_W_new.a)
}
inline const ::google::protobuf::RepeatedField< double >&
Args_State_m_W_new::a() const {
  // @@protoc_insertion_point(field_list:advance.Args.State.m_W_new.a)
  return a_;
}
inline ::google::protobuf::RepeatedField< double >*
Args_State_m_W_new::mutable_a() {
  // @@protoc_insertion_point(field_mutable_list:advance.Args.State.m_W_new.a)
  return &a_;
}

// -------------------------------------------------------------------

// Args_State_m_R

// repeated double a = 1 [packed = true];
inline int Args_State_m_R::a_size() const {
  return a_.size();
}
inline void Args_State_m_R::clear_a() {
  a_.Clear();
}
inline double Args_State_m_R::a(int index) const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_R.a)
  return a_.Get(index);
}
inline void Args_State_m_R::set_a(int index, double value) {
  a_.Set(index, value);
  // @@protoc_insertion_point(field_set:advance.Args.State.m_R.a)
}
inline void Args_State_m_R::add_a(double value) {
  a_.Add(value);
  // @@protoc_insertion_point(field_add:advance.Args.State.m_R.a)
}
inline const ::google::protobuf::RepeatedField< double >&
Args_State_m_R::a() const {
  // @@protoc_insertion_point(field_list:advance.Args.State.m_R.a)
  return a_;
}
inline ::google::protobuf::RepeatedField< double >*
Args_State_m_R::mutable_a() {
  // @@protoc_insertion_point(field_mutable_list:advance.Args.State.m_R.a)
  return &a_;
}

// -------------------------------------------------------------------

// Args_State_m_Vbar_prime

// repeated double a = 1 [packed = true];
inline int Args_State_m_Vbar_prime::a_size() const {
  return a_.size();
}
inline void Args_State_m_Vbar_prime::clear_a() {
  a_.Clear();
}
inline double Args_State_m_Vbar_prime::a(int index) const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_Vbar_prime.a)
  return a_.Get(index);
}
inline void Args_State_m_Vbar_prime::set_a(int index, double value) {
  a_.Set(index, value);
  // @@protoc_insertion_point(field_set:advance.Args.State.m_Vbar_prime.a)
}
inline void Args_State_m_Vbar_prime::add_a(double value) {
  a_.Add(value);
  // @@protoc_insertion_point(field_add:advance.Args.State.m_Vbar_prime.a)
}
inline const ::google::protobuf::RepeatedField< double >&
Args_State_m_Vbar_prime::a() const {
  // @@protoc_insertion_point(field_list:advance.Args.State.m_Vbar_prime.a)
  return a_;
}
inline ::google::protobuf::RepeatedField< double >*
Args_State_m_Vbar_prime::mutable_a() {
  // @@protoc_insertion_point(field_mutable_list:advance.Args.State.m_Vbar_prime.a)
  return &a_;
}

// -------------------------------------------------------------------

// Args_State_m_Vbar_prime_dot

// repeated double a = 1 [packed = true];
inline int Args_State_m_Vbar_prime_dot::a_size() const {
  return a_.size();
}
inline void Args_State_m_Vbar_prime_dot::clear_a() {
  a_.Clear();
}
inline double Args_State_m_Vbar_prime_dot::a(int index) const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_Vbar_prime_dot.a)
  return a_.Get(index);
}
inline void Args_State_m_Vbar_prime_dot::set_a(int index, double value) {
  a_.Set(index, value);
  // @@protoc_insertion_point(field_set:advance.Args.State.m_Vbar_prime_dot.a)
}
inline void Args_State_m_Vbar_prime_dot::add_a(double value) {
  a_.Add(value);
  // @@protoc_insertion_point(field_add:advance.Args.State.m_Vbar_prime_dot.a)
}
inline const ::google::protobuf::RepeatedField< double >&
Args_State_m_Vbar_prime_dot::a() const {
  // @@protoc_insertion_point(field_list:advance.Args.State.m_Vbar_prime_dot.a)
  return a_;
}
inline ::google::protobuf::RepeatedField< double >*
Args_State_m_Vbar_prime_dot::mutable_a() {
  // @@protoc_insertion_point(field_mutable_list:advance.Args.State.m_Vbar_prime_dot.a)
  return &a_;
}

// -------------------------------------------------------------------

// Args_State_m_Dbar_prime

// repeated double a = 1 [packed = true];
inline int Args_State_m_Dbar_prime::a_size() const {
  return a_.size();
}
inline void Args_State_m_Dbar_prime::clear_a() {
  a_.Clear();
}
inline double Args_State_m_Dbar_prime::a(int index) const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_Dbar_prime.a)
  return a_.Get(index);
}
inline void Args_State_m_Dbar_prime::set_a(int index, double value) {
  a_.Set(index, value);
  // @@protoc_insertion_point(field_set:advance.Args.State.m_Dbar_prime.a)
}
inline void Args_State_m_Dbar_prime::add_a(double value) {
  a_.Add(value);
  // @@protoc_insertion_point(field_add:advance.Args.State.m_Dbar_prime.a)
}
inline const ::google::protobuf::RepeatedField< double >&
Args_State_m_Dbar_prime::a() const {
  // @@protoc_insertion_point(field_list:advance.Args.State.m_Dbar_prime.a)
  return a_;
}
inline ::google::protobuf::RepeatedField< double >*
Args_State_m_Dbar_prime::mutable_a() {
  // @@protoc_insertion_point(field_mutable_list:advance.Args.State.m_Dbar_prime.a)
  return &a_;
}

// -------------------------------------------------------------------

// Args_State_m_Wbar

// repeated double a = 1 [packed = true];
inline int Args_State_m_Wbar::a_size() const {
  return a_.size();
}
inline void Args_State_m_Wbar::clear_a() {
  a_.Clear();
}
inline double Args_State_m_Wbar::a(int index) const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_Wbar.a)
  return a_.Get(index);
}
inline void Args_State_m_Wbar::set_a(int index, double value) {
  a_.Set(index, value);
  // @@protoc_insertion_point(field_set:advance.Args.State.m_Wbar.a)
}
inline void Args_State_m_Wbar::add_a(double value) {
  a_.Add(value);
  // @@protoc_insertion_point(field_add:advance.Args.State.m_Wbar.a)
}
inline const ::google::protobuf::RepeatedField< double >&
Args_State_m_Wbar::a() const {
  // @@protoc_insertion_point(field_list:advance.Args.State.m_Wbar.a)
  return a_;
}
inline ::google::protobuf::RepeatedField< double >*
Args_State_m_Wbar::mutable_a() {
  // @@protoc_insertion_point(field_mutable_list:advance.Args.State.m_Wbar.a)
  return &a_;
}

// -------------------------------------------------------------------

// Args_State_taylor_state

// repeated double a = 1 [packed = true];
inline int Args_State_taylor_state::a_size() const {
  return a_.size();
}
inline void Args_State_taylor_state::clear_a() {
  a_.Clear();
}
inline double Args_State_taylor_state::a(int index) const {
  // @@protoc_insertion_point(field_get:advance.Args.State.taylor_state.a)
  return a_.Get(index);
}
inline void Args_State_taylor_state::set_a(int index, double value) {
  a_.Set(index, value);
  // @@protoc_insertion_point(field_set:advance.Args.State.taylor_state.a)
}
inline void Args_State_taylor_state::add_a(double value) {
  a_.Add(value);
  // @@protoc_insertion_point(field_add:advance.Args.State.taylor_state.a)
}
inline const ::google::protobuf::RepeatedField< double >&
Args_State_taylor_state::a() const {
  // @@protoc_insertion_point(field_list:advance.Args.State.taylor_state.a)
  return a_;
}
inline ::google::protobuf::RepeatedField< double >*
Args_State_taylor_state::mutable_a() {
  // @@protoc_insertion_point(field_mutable_list:advance.Args.State.taylor_state.a)
  return &a_;
}

// -------------------------------------------------------------------

// Args_State

// required double m_Delta_max = 1;
inline bool Args_State::has_m_delta_max() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Args_State::set_has_m_delta_max() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Args_State::clear_has_m_delta_max() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Args_State::clear_m_delta_max() {
  m_delta_max_ = 0;
  clear_has_m_delta_max();
}
inline double Args_State::m_delta_max() const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_Delta_max)
  return m_delta_max_;
}
inline void Args_State::set_m_delta_max(double value) {
  set_has_m_delta_max();
  m_delta_max_ = value;
  // @@protoc_insertion_point(field_set:advance.Args.State.m_Delta_max)
}

// required double m_Delta = 2;
inline bool Args_State::has_m_delta() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Args_State::set_has_m_delta() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Args_State::clear_has_m_delta() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Args_State::clear_m_delta() {
  m_delta_ = 0;
  clear_has_m_delta();
}
inline double Args_State::m_delta() const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_Delta)
  return m_delta_;
}
inline void Args_State::set_m_delta(double value) {
  set_has_m_delta();
  m_delta_ = value;
  // @@protoc_insertion_point(field_set:advance.Args.State.m_Delta)
}

// required double m_J = 3;
inline bool Args_State::has_m_j() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Args_State::set_has_m_j() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Args_State::clear_has_m_j() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Args_State::clear_m_j() {
  m_j_ = 0;
  clear_has_m_j();
}
inline double Args_State::m_j() const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_J)
  return m_j_;
}
inline void Args_State::set_m_j(double value) {
  set_has_m_j();
  m_j_ = value;
  // @@protoc_insertion_point(field_set:advance.Args.State.m_J)
}

// required int32 m_num_iters = 4;
inline bool Args_State::has_m_num_iters() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Args_State::set_has_m_num_iters() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Args_State::clear_has_m_num_iters() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Args_State::clear_m_num_iters() {
  m_num_iters_ = 0;
  clear_has_m_num_iters();
}
inline ::google::protobuf::int32 Args_State::m_num_iters() const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_num_iters)
  return m_num_iters_;
}
inline void Args_State::set_m_num_iters(::google::protobuf::int32 value) {
  set_has_m_num_iters();
  m_num_iters_ = value;
  // @@protoc_insertion_point(field_set:advance.Args.State.m_num_iters)
}

// required double m_volume_change = 5;
inline bool Args_State::has_m_volume_change() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Args_State::set_has_m_volume_change() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Args_State::clear_has_m_volume_change() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Args_State::clear_m_volume_change() {
  m_volume_change_ = 0;
  clear_has_m_volume_change();
}
inline double Args_State::m_volume_change() const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_volume_change)
  return m_volume_change_;
}
inline void Args_State::set_m_volume_change(double value) {
  set_has_m_volume_change();
  m_volume_change_ = value;
  // @@protoc_insertion_point(field_set:advance.Args.State.m_volume_change)
}

// required double m_tol = 6;
inline bool Args_State::has_m_tol() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Args_State::set_has_m_tol() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Args_State::clear_has_m_tol() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Args_State::clear_m_tol() {
  m_tol_ = 0;
  clear_has_m_tol();
}
inline double Args_State::m_tol() const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_tol)
  return m_tol_;
}
inline void Args_State::set_m_tol(double value) {
  set_has_m_tol();
  m_tol_ = value;
  // @@protoc_insertion_point(field_set:advance.Args.State.m_tol)
}

// required double m_K = 7;
inline bool Args_State::has_m_k() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Args_State::set_has_m_k() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Args_State::clear_has_m_k() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Args_State::clear_m_k() {
  m_k_ = 0;
  clear_has_m_k();
}
inline double Args_State::m_k() const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_K)
  return m_k_;
}
inline void Args_State::set_m_k(double value) {
  set_has_m_k();
  m_k_ = value;
  // @@protoc_insertion_point(field_set:advance.Args.State.m_K)
}

// required double m_G = 8;
inline bool Args_State::has_m_g() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Args_State::set_has_m_g() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Args_State::clear_has_m_g() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Args_State::clear_m_g() {
  m_g_ = 0;
  clear_has_m_g();
}
inline double Args_State::m_g() const {
  // @@protoc_insertion_point(field_get:advance.Args.State.m_G)
  return m_g_;
}
inline void Args_State::set_m_g(double value) {
  set_has_m_g();
  m_g_ = value;
  // @@protoc_insertion_point(field_set:advance.Args.State.m_G)
}

// -------------------------------------------------------------------

// Args

// required double delta_t = 1;
inline bool Args::has_delta_t() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Args::set_has_delta_t() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Args::clear_has_delta_t() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Args::clear_delta_t() {
  delta_t_ = 0;
  clear_has_delta_t();
}
inline double Args::delta_t() const {
  // @@protoc_insertion_point(field_get:advance.Args.delta_t)
  return delta_t_;
}
inline void Args::set_delta_t(double value) {
  set_has_delta_t();
  delta_t_ = value;
  // @@protoc_insertion_point(field_set:advance.Args.delta_t)
}

// required double volume_change = 2;
inline bool Args::has_volume_change() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Args::set_has_volume_change() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Args::clear_has_volume_change() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Args::clear_volume_change() {
  volume_change_ = 0;
  clear_has_volume_change();
}
inline double Args::volume_change() const {
  // @@protoc_insertion_point(field_get:advance.Args.volume_change)
  return volume_change_;
}
inline void Args::set_volume_change(double value) {
  set_has_volume_change();
  volume_change_ = value;
  // @@protoc_insertion_point(field_set:advance.Args.volume_change)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace advance

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_advance_2eproto__INCLUDED
